# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


use_frameworks!

def shared_pods
    pod 'CoreGPX', git: 'https://github.com/VincentNeo/CoreGPX.git'
    pod 'CryptoSwift', git: 'https://github.com/krzyzanowskim/CryptoSwift'
end

target 'TrackLocation' do
    platform :ios, '8.0'
    shared_pods
    pod 'Cache', git: 'https://github.com/hyperoslo/Cache'
end

